name: api tests

on:
  push:
    branches:
      - 'feature/*' 
      
  pull_request:

env:
  GITHUB_REGISTRY: ghcr.io

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker compose
      run: docker-compose up -d
    - name: Run Karate tests
      run: |
        docker-compose up --abort-on-container-exit --exit-code-from karate-tests
        exit_code=$?
        if [ $exit_code -eq 0 ]; then
          echo "Tests passed successfully!"
        else
          echo "Tests failed!"
          exit 1
        fi