name: Karate Tests with Docker Compose

on:
  push:
    branches:
      - feature/*

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.9
        options: --privileged
        ports:
          - 8080:8080
          - 5432:5432
        command: ["dockerd-entrypoint.sh"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Compose
      run: |
        docker-compose --version
        sudo rm /usr/local/bin/docker-compose
        curl -L https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    - name: Start services
      run: docker-compose up -d

    - name: Wait for services to be ready
      run: |
        until $(curl --output /dev/null --silent --head --fail http://localhost:35000/actuator/health); do
          printf '.'
          sleep 5
        done

    - name: Run Karate Tests
      run: |
        ./gradlew test
