name: api tests

on:
  push:
    branches:
      - 'feature/*' 
      
  pull_request:

env:
  GITHUB_REGISTRY: ghcr.io

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
    - name: Docker compose
        run: docker-compose up -d

    - name: API tests
      uses: erikbos/karate-action@main
      with:
        url: http://localhost:35000/
        tests: |
          Api/E2E/ToDoControllerEnd-to-EndTesting.feature