name: api tests

on:
  push:
    branches:
      - 'feature/*' 
      
  pull_request:

env:
  GITHUB_REGISTRY: ghcr.io
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0

    - name: Restore application dependencies
        run: dotnet restore

    - name: Build application
      run: dotnet build

    - name: API tests
      uses: erikbos/karate-action@main
      with:
        url: https://localhost:35000/
        tests: |
          Api/E2E/ToDoControllerEnd-to-EndTesting.feature