name: api tests

on:
  push:
    branches:
      - 'feature/*' 
      
  pull_request:

env:
  GITHUB_REGISTRY: ghcr.io

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker compose
      run: docker-compose up -d
    - name: Run Karate tests
      run: |
        docker-compose up --abort-on-container-exit
    - name: Extract test results
      run: |
        PASSED=$(docker-compose logs karate-tests | grep "passed:" | sed 's/.*passed: *\([0-9]*\).*/\1/')
        FAILED=$(docker-compose logs karate-tests | grep "failed:" | sed 's/.*failed: *\([0-9]*\).*/\1/')
        echo "Passed tests: $PASSED"
        echo "Failed tests: $FAILED"
        if [ $FAILED -gt 0 ]; then
          echo "Failed tests found! Failing the pipeline..."
          exit 1
        fi